### ISSUE TITLE
Cannot compile: imgui.h errors

### ISSUE THREAD

**Issue by dc0x45** [Martymoose98/2BHook#9]
Hello, I am trying to compile this on windows 10 with visual studio 2022. However, every time I do, I run into a gamut of errors which all fall along the lines of "redefinition of default argument" (regarding imgui, not your code). Could you please provide compilation instructions and/or provide an updated DLL? 

Thank you for your time
!

**Comment by xxk-i** [comment]
Hi dc0x45, ensure that the repo is cloned completely and recursively so that imgui is fully populated with its files. Additionally, you can try adding " $(SolutionDir)imgui; " to the Additional Include Directories in the project properties. If you try this and still get errors, please paste some of them in your comment.

**Comment by Martymoose98** [comment]
Can you provide a picture of the error(s) in visual studio?
